name: Run Python Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Build and run the application
        run: docker compose up --build -d

      - name: Wait for API to be healthy
        run: |
          # Wait for up to 30 seconds for the API to respond
          timeout 30s bash -c 'until curl -s http://localhost:8000/docs > /dev/null; do echo "Waiting for API server..."; sleep 2; done'

      - name: Set up Python for test runner
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install test dependencies
        run: pip install -e ".[test]"

      - name: Run tests
        # The tests run on the host runner, connecting to the services
        # exposed by Docker Compose on localhost.
        run: pytest

      - name: Show container logs on failure
        if: failure()
        run: docker compose logs