name: Run Python Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: briefing_user
          POSTGRES_PASSWORD: a_secure_password
          POSTGRES_DB: briefing_db_test
        options: >-
          --health-cmd "pg_isready -U briefing_user -d briefing_db_test"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # Step 1: Check out the repository's code onto the runner.
      - name: Check out repository code
        uses: actions/checkout@v4

      # Step 2: Set up Python 3.11
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Step 3: Install project dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[test]"

      # Step 4: Run tests with pytest
      - name: Run tests with pytest
        env:
          DB_HOST: localhost
          DB_PORT: 5432
          DB_USER: briefing_user
          DB_PASSWORD: a_secure_password
          DB_NAME: briefing_db_test
          WEATHER_API_KEY: "dummy_key_for_ci"
        run: pytest